- name: Provision Frontend VM
  hosts: all
  become: true

  vars:
    docker_packages:
      - docker.io
      - docker-compose-plugin

  tasks:
    - name: Update & Upgrade packages
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Remove conflicting containerd if present
      ansible.builtin.apt:
        name: containerd
        state: absent
      ignore_errors: yes

    - name: Install Docker packages
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: yes

    - name: Docker login GHCR
      community.docker.docker_login:
        registry_url: ghcr.io
        username: "{{ registry_username }}"
        password: "{{ registry_token }}"

    - name: Create app directory
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/app"
        state: directory
        mode: "0755"

    - name: Deploy docker-compose.yml
      ansible.builtin.template:
        src: "/tmp/docker-compose.yml.j2"
        dest: "/home/{{ ansible_user }}/app/docker-compose.yml"

    - name: Launch Docker Compose
      community.docker.docker_compose_v2:
        project_src: "/home/{{ ansible_user }}/app"
        state: present

    - name: Afficher l'IP publique de la VM
      ansible.builtin.shell: "curl -s ifconfig.me"
      register: vm_ip

    - name: Print deployed frontend URL
      ansible.builtin.debug:
        msg: "Votre frontend est en ligne : http://{{ vm_ip.stdout }}:8080"