- name: Provision Frontend VM
  hosts: all
  become: true

  vars:
    docker_apt_packages:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Remove conflicting containerd (if any)
      ansible.builtin.apt:
        name: containerd
        state: absent
      ignore_errors: yes

    - name: Wait for APT lock to be released
      shell: |
        while fuser /var/lib/dpkg/lock >/dev/null 2>&1 || \
              fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Waiting for apt lock..."
          sleep 5
        done
      changed_when: false

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name: "{{ docker_apt_packages }}"
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Update APT cache after adding Docker repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker packages
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: present

    - name: Docker login GHCR
      community.docker.docker_login:
        registry_url: ghcr.io
        username: "{{ registry_username }}"
        password: "{{ registry_token }}"

    - name: Create app directory
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/app"
        state: directory
        mode: "0755"

    - name: Deploy docker-compose.yml
      ansible.builtin.template:
        src: "/tmp/docker-compose.yml.j2"
        dest: "/home/{{ ansible_user }}/app/docker-compose.yml"

    - name: Launch Docker Compose
      community.docker.docker_compose_v2:
        project_src: "/home/{{ ansible_user }}/app"
        state: present

    - name: Get public IP
      ansible.builtin.shell: "curl -s ifconfig.me"
      register: vm_ip

    - name: Print deployed frontend URL
      ansible.builtin.debug:
        msg: "Votre frontend est en ligne : http://{{ vm_ip.stdout }}:8080"