- name: Provision Frontend VM
  hosts: all
  become: true

  vars:
    docker_packages:
      - docker.io
      - docker-compose-plugin

  tasks:
    - name: Update & Upgrade packages
      apt:
        upgrade: dist
        update_cache: yes

    - name: Install Docker
      apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: yes

    - name: Docker login GHCR
      community.docker.docker_login:
        registry_url: ghcr.io
        username: "{{ registry_username }}"
        password: "{{ registry_token }}"

    - name: Create app directory
      file:
        path: "/home/{{ ansible_user }}/app"
        state: directory
        mode: "0755"

    - name: Deploy docker-compose.yml
      template:
        src: "/tmp/docker-compose.yml.j2"
        dest: "/home/{{ ansible_user }}/app/docker-compose.yml"

    - name: Launch Docker Compose
      community.docker.docker_compose_v2:
        project_src: "/home/{{ ansible_user }}/app"
        state: present