name: Deploy Frontend VM

on:
  workflow_dispatch:  # Lancement manuel depuis l'interface GitHub

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var="api_token=${{ secrets.API_TOKEN }}" \
            -var="ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }}" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var="username=${{ secrets.ANSIBLE_USER }}" \
            -var="registry_username=${{ github.repository_owner }}" \
            -var="registry_token=${{ secrets.REGISTRY_TOKEN }}" \
            -var="front_image_tag=ghcr.io/${{ github.repository_owner }}/breizhsport_front:infra"

      - name: Cleanup
        run: rm -f terraform/id_rsa
