name: Snyk Security Analysis

on:
  # Ce workflow se déclenche lorsqu'il y a un push ou une pull request sur la branche main,
  # ainsi que lors d'un déclenchement manuel (workflow_dispatch).
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk:
    name: Run Snyk Security Scan
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code source du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installe la CLI Snyk (dernière version)
      - name: Set up Snyk
        uses: snyk/actions/setup@master
        with:
          version: "latest"

      # 3. Authentifie Snyk avec le token stocké dans les secrets GitHub
      - name: Authenticate Snyk
        run: snyk auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 4. Analyse les dépendances de tous les projets détectés pour trouver des vulnérabilités
      - name: Test for vulnerabilities
        run: snyk test --all-projects --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 5. (Optionnel) Envoie les informations du projet à Snyk pour un suivi continu
      - name: Monitor project in Snyk
        run: snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
